[general]
server_check_url = http://cp.cloudflare.com/generate_204
network_check_url = http://wifi.vivo.com.cn/generate_204
dns_exclusion_list = *.cmpassport.com, *.jegotrip.com.cn, *.icitymobile.mobi, *.alipay.com, *.tmall.com, *.qq.com, id6.me
fallback_udp_policy = reject

[dns]
no-ipv6
no-system
server = 223.5.5.5
server = 119.29.29.29
doh-server = https://doh.pub/dns-query, https://dns.alidns.com/dns-query

[policy]
static=Hong Kong, resource-tag-regex=.*, server-tag-regex=🇭🇰|港|HK|Hong|hong|香港
static=Taiwan, resource-tag-regex=.*, server-tag-regex=🇹🇼|台|TW|Tai|Taiwan|台湾|台灣
static=Singapore, resource-tag-regex=.*, server-tag-regex=🇸🇬|新加坡|坡|狮城|SG|Singapore
static=United States, resource-tag-regex=.*, server-tag-regex=🇺🇸|美|洛杉矶|圣何塞|圣克拉拉|西雅图|硅谷|US|USA|美国

static=Netflix, Singapore, Hong Kong, Taiwan
static=YouTube, United States, Singapore, Hong Kong, Taiwan
static=Spotify, Hong Kong, Singapore, United States, Taiwan, direct

[server_remote]
https://em.mesl.cloud/ems/get?token=e2176343ebe461b69ed0f4430b8fec32, tag=MESL, update-interval=-1, opt-parser=false, enabled=true

[filter_remote]

# Siri AI / Apple Intelligence
https://raw.githubusercontent.com/allg00dman/rule/refs/heads/main/QuantumultX/SiriAI.list, tag=SiriAI, force-policy=United States, update-interval=86400, opt-parser=false, enabled=true

# Apple
https://raw.githubusercontent.com/allg00dman/ios_rule_script/master/rule/QuantumultX/Apple/Apple.list, tag=Apple, force-policy=direct, update-interval=86400, opt-parser=false, enabled=true

# NBA
https://raw.githubusercontent.com/allg00dman/rule/refs/heads/main/QuantumultX/NBA.list, tag=NBA, force-policy=Taiwan, update-interval=86400, opt-parser=false, enabled=true

# Netflix
https://raw.githubusercontent.com/allg00dman/ios_rule_script/master/rule/QuantumultX/Netflix/Netflix.list, tag=Netflix, force-policy=Netflix, update-interval=86400, opt-parser=false, enabled=true

# Spotify
https://raw.githubusercontent.com/allg00dman/ios_rule_script/master/rule/QuantumultX/Spotify/Spotify.list, tag=Spotify, force-policy=Spotify, update-interval=86400, opt-parser=false, enabled=true

# YouTube
https://raw.githubusercontent.com/allg00dman/ios_rule_script/master/rule/QuantumultX/YouTube/YouTube.list, tag=YouTube, force-policy=YouTube, update-interval=86400, opt-parser=false, enabled=true

# YouTube Music
https://raw.githubusercontent.com/allg00dman/ios_rule_script/master/rule/QuantumultX/YouTubeMusic/YouTubeMusic.list, tag=YouTubeMusic, force-policy=YouTube, update-interval=86400, opt-parser=false, enabled=true

# OpenAI
https://raw.githubusercontent.com/allg00dman/ios_rule_script/master/rule/QuantumultX/OpenAI/OpenAI.list, tag=OpenAI, force-policy=United States, update-interval=86400, opt-parser=false, enabled=true

# Claude
https://raw.githubusercontent.com/allg00dman/ios_rule_script/master/rule/QuantumultX/Claude/Claude.list, tag=Claude, force-policy=United States, update-interval=86400, opt-parser=false, enabled=true

# Google
https://raw.githubusercontent.com/allg00dman/ios_rule_script/master/rule/QuantumultX/Google/Google.list, tag=Google, force-policy=Taiwan, update-interval=86400, opt-parser=false, enabled=true

# 中国大陆
FILTER_REGION, tag=CN, force-policy=direct, inserted-resource=true, enabled=true

# 局域网
FILTER_LAN, tag=LAN, force-policy=direct, inserted-resource=true, enabled=true

[filter_local]
host-suffix, push.apple.com, Hong Kong
host-keyword, courier, Hong Kong
final, Proxy

[server_local]

[rewrite_remote]

[rewrite_local]

[mitm]
